name: Benchmark

on:
  workflow_dispatch:  # can be run on-demand
  schedule:
    - cron: '0 2 * * 0'  # Weekly run on Sundays at 2 AM (automated benchmarking)

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t banner-service-benchmark .

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/generated" >> $GITHUB_ENV

    - name: Run Docker Container for Benchmarking
      run: |
        docker run --rm banner-service-benchmark

    - name: Verify Benchmark Results
      run: ls -lh locust_logs/

    - name: Upload Benchmark Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: locust_logs/

